
test:
	python -m unittest tests.test_logSpider
	python -m unittest tests.test_finder


build:
	python setup.py build

bdist_egg:
	python setup.py bdist_egg

sdist:
	python setup.py sdist

install:
	python setup.py install

develop:
	python setup.py develop


clean:
	rm -rf build
	rm -rf dist
	rm -rf LogSpider.egg-info


