version: '3'


services:

  logspider:
    image: my.com:1333/chase/cmdsvr
    #ports:
    #  - 9000:9000
    volumes:
      - D:/LogSpider:/usr/src/app
      - D:/log:/usr/src/log
      - D:/classified_log:/usr/src/classified_log
    command: python /usr/src/app/Spider.py
    #command: sh
